name: Linting

on:
  push:
    branches:
      - "*"
      - "feature/*"
    paths:
      - "**.js*"
      - "**.ts*"
      - "package*.json"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.js*"
      - "**.ts*"
      - "package*.json"
      - ".github/workflows/lint.yml"

env:
  NODE_VERSION: 14

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install modules
        run: yarn

      - name: Liting
        run: yarn lint
